#FROM ubuntu:latest
#MAINTAINER ky "gil9103@gmail.com"
#RUN apt-get update -y
#RUN apt-get install -y python3 python3-pip build-essential git
#
#RUN git clone https://github.com/crazyboy9103/ambient_fl
#
#RUN pip3 install keras Keras-Applications Keras-Preprocessing requests tensorflow tensorflow-gpu numpy
#WORKDIR /ambient_fl